### ISSUE TITLE
internal checkBounds() fails

### ISSUE THREAD

**Issue by camrinbraun** [rmendels/rerddapXtracto#11]
The internal `checkBounds` is suddenly failing, perhaps due to updating the package. I tried updating to both of the latest branches on Github, including dependencies, with no change.

The issue arises when using any of the `rxtracto...` functions.

``` r
## rxtracto
dataInfo <- rerddap::info('erdHadISST')

parameter <- 'sst'
xcoord <- c(-130.5)
ycoord <- c(40.5)
tcoord <- c('2006-01-16')
xlen <- 0.01
ylen <- 0.01
extract <- rxtracto(dataInfo, parameter = parameter, xcoord = xcoord,
                    ycoord = ycoord, tcoord= tcoord,
                    xlen = xlen, ylen = ylen)
```
Error in if ((min_dimargs < min_coord) | (max_dimargs > max_coord)) { : 
  missing value where TRUE/FALSE needed

``` r
## rxtractogon (WHICH USES rxtracto_3d)
dataInfo <- rerddap::info('erdHadISST')

parameter <- 'sst'
tcoord <- c("2016-06-15")
xcoord <- mbnms$Longitude[1:3]
ycoord <- mbnms$Latitude[1:3]
sanctSST <- rxtractogon (dataInfo, parameter=parameter, xcoord = xcoord,
                         ycoord = ycoord,  tcoord= tcoord)
```
Error in if ((min_dimargs < min_coord) | (max_dimargs > max_coord)) { : 
  missing value where TRUE/FALSE needed

**Comment by rmendels** [comment]
We are in the midst of installing a new version of ERDDAP.  It takes a long time to load all the datasets when starting from scratch.  I would suggest waiting till tomorrow morning and seeing if the problem goes away

**Comment by rmendels** [comment]
@camrinbraun forgot to @ you so I am sure you see this

We are in the midst of installing a new version of ERDDAP. It takes a long time to load all the datasets when starting from scratch. I would suggest waiting till tomorrow morning and seeing if the problem goes away

**Comment by camrinbraun** [comment]
Works fine this morning. 

Just a suggestion to push some kind of warning to the user when there are server-side issues or maintenance like this so people like me don't bug you ;)
