### ISSUE TITLE
Extracting HYCOM data from ERDDAP

### ISSUE THREAD

**Issue by mebowers5** [rmendels/rerddapXtracto#19]
Hi!

HYCOM data uses "depth" instead of "altitude." Any suggestion for a workaround there? 

> TagData<-males
> xpos<-TagData$x2
> ypos<-TagData$Latitude
> tpos<-TagData$detection_timestamp_utc
> zpos <- rep(3., length(xpos))
> urlBase <- "https://upwell.pfeg.noaa.gov/erddap/"
> salInfo <- rerddap::info('nrlHycomGLBu008e911D', url = urlBase)
> YourDataEnv <- rxtracto(salInfo, parameter = 'salinity', xcoord=xpos, ycoord=ypos, tcoord=tpos, zcoord=zpos, xlen=0.05, ylen=0.05)
[1] "Requested coordinate names do no match dataset coordinate names"
[1] "Requested coordinate names: longitude"
[2] "Requested coordinate names: latitude" 
[3] "Requested coordinate names: altitude" 
[4] "Requested coordinate names: time"     
[1] "Dataset coordinate names: time"      "Dataset coordinate names: depth"    
[3] "Dataset coordinate names: latitude"  "Dataset coordinate names: longitude"
Error: Execution halted

**Comment by rmendels** [comment]
Um yes,  I do have a "workaround".  The default call to `rxtracto()` as defined in the docs is:

```r
rxtracto <- function(dataInfo, parameter = NULL, xcoord = NULL, ycoord = NULL, zcoord = NULL, tcoord = NULL, xlen = 0., ylen = 0., zlen = 0., xName = 'longitude', yName = 'latitude', zName = 'altitude', tName = 'time', urlbase = 'http://upwell.pfeg.noaa.gov/erddap', verbose = FALSE)
```
so just set the value of `zName` to depth.

**Comment by mebowers5** [comment]
Thank you! I was way overthinking it. That worked great but I had to rerun all of the other associated functions as well.
