### ISSUE TITLE
80 char width max for man files and code

### ISSUE THREAD

**Issue by sckott** [rmendels/rerddapXtracto#2]
I would strive for that if possible - then the pdf manual won't lose any text

**Comment by rmendels** [comment]
Thanks.  Yeah devtools::check() was complaining about that also.  Haven't had time to go and fix it.

-Roy
> On Jan 4, 2017, at 9:35 AM, Scott Chamberlain <notifications@github.com> wrote:
> 
> I would strive for that if possible - then the pdf manual won't lose any text
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.
