### ISSUE TITLE
rxtracto() error downloading subset 

### ISSUE THREAD

**Issue by makratofil** [rmendels/rerddapXtracto#22]
Hi Roy,

I'm extracting some data for a series of tag deployments and keep running into an error when I try to download a particular variable from a dataset. There are 2 variables that I'm interested in extracting from this dataset, evel and nvel (eastward and northward current velocity). I've been able to extract 'nvel' without error but for some reason when I try to extract 'evel' the extraction progresses to about 78% then spits out the following error:

```{r}
"error in trying to download the subset"
[1] "check your settings"
$x
<ERDDAP info> hawaii_soest_cca9_a73c_ef70 
Base URL: https://apdrc.soest.hawaii.edu/erddap/ 
  Dimensions (range):  
  time: (2007-06-23T00:00:00Z, 2018-11-27T00:00:00Z) 
LEV: (0.0, 5500.0) 
latitude: (10.028, 39.915) 
longitude: (170.0, 219.92) 
Variables:  
  dens: 
evel: 
  Units: m s-1 
nvel: 
  Units: m s-1 
saln: 
  Units: PSU 
temp: 
  wvel: 
  Units: m s-1 

$url
[1] "https://apdrc.soest.hawaii.edu/erddap/"

$longitude
[1] 202 202

$latitude
[1] 23.474 23.474

$LEV
[1] 0 0

$time
[1] "2014-10-16T00:00:00Z" "2014-10-16T00:00:00Z"

$fields
[1] "evel"

$read
[1] FALSE

[1] "stopping execution  - will return what has been downloaded so far"
[1] "There was an error in the url call, perhaps a time out. See message on screen and URL called"
[1] "Returning incomplete download"
Error in UseMethod("cache_delete") : 
  no applicable method for 'cache_delete' applied to an object of class "c('double', 'numeric')"
In addition: Warning message:
  In remove("paramdata") : object 'paramdata' not found
```
It's interesting because the latitude that the error lists is not included in the ycoord of the dataset that I provided (accounting for 0.01 ylen). I've provided my code below and attached the particular portion of the dataset as an .rds file (within zip) that seems to generate this error. 
[rxtracto error data.zip](https://github.com/rmendels/rerddapXtracto/files/4885973/rxtracto.error.data.zip)

```{r}
# set variable information
xpos <- gis.locs$longitud
ypos <- gis.locs$latitude
tpos <- gis.locs$Date_ymd
zpos <- rep(0., length(xpos)) # set altitude to zero 

currInfo <- rerddap::info('hawaii_soest_cca9_a73c_ef70', url = 'https://apdrc.soest.hawaii.edu/erddap/')

# northward current velocity
v <- rxtracto(currInfo, parameter = 'nvel', xcoord = xpos, ycoord = ypos, tcoord = tpos, zcoord = zpos,
              zName = 'LEV', xlen = 0.01, ylen = 0.01, progress_bar = T)

# eastward current velocity
u <- rxtracto(currInfo, parameter = 'evel', xcoord = xpos, ycoord = ypos, tcoord = tpos, zcoord = zpos,
             zName = 'LEV', xlen = 0.01, ylen = 0.01, progress_bar = T)
```
Any thoughts would be greatly appreciated!

**Comment by rmendels** [comment]
I will look at this when I have time.  In regards to your comment on the latitude,  at the end of the vignette there is a description of what the algorithm does.  In order not to repeat what will essentially be the same request,  it takes your actual coordinate values at that one point,  and finds the closest grid point in the ERDDAP dataset,  and makes that request.  So 'rxtracto()' if working correctly,  always makes requests at actual gridpoints.  I would add that for a large datasets like the hycom,  the Hawaii server can often time out.  Which is why the function returns what it has so far,  so you can restart from there.  But I will double check it.

**Comment by rmendels** [comment]
@makratofil forget to '@' you in my first response.  Pleas look at the issue page.

**Comment by makratofil** [comment]
@rmendels Thank you! I actually just found another dataset that seems to work fine for running that particular subset of data separately, so can close this issue. I did run the data separately using the dataset I initially used and encountered the same error, so must be an issue associated with the server.

**Comment by rmendels** [comment]
@makratofil  - I will check it anyway.  There may be lurking errors in the code,  particularly for datasets in the (x,y,z,t) plane because that doesn't get tested a lot.   Will let you know.

**Comment by rmendels** [comment]
@makratofil  I am getting certificate problems with the Hawaii server again,  so I can't get in and reproduce what you have done.

**Comment by makratofil** [comment]
@rmendels No worries- I'm assuming the issue I had are related to the server, as I've been using the same datasets on a different set of location data today and haven't ran into the same issue thus far!
