### ISSUE TITLE
Integrate Interpolate feature into rextracto

### ISSUE THREAD

**Issue by SimonDedman** [rmendels/rerddapXtracto#25]
[Interpolate](https://coastwatch.pfeg.noaa.gov/erddap/convert/interpolate.html) gives the user options to download data typically corresponding to lat-lon points, from gridded datasets, interpolating the results to the users actual locations (from the dataset grid locations). Roy is planning on adding this already, this is just a note to track it here :)

**Comment by rmendels** [comment]
@SimonDedman   BTW - I am closing this because the present version has the feature.  Forget to add that here  (something about old age and .....)

**Comment by SimonDedman** [comment]
Cheers for keeping me posted bud 😂
