### ISSUE TITLE
Extrating sea ice data from polar watch

### ISSUE THREAD

**Issue by MarieAugerMethe** [rmendels/rerddapXtracto#29]
Dear Roy,

thank you for the wonderful package!!

I'm trying to extract sea ice concentration data from a polygon and I am running into a bunch of issues. Here my most recent attempt and the error I get.

```library(sf)
library(sf)
library(ggplot2)
library(rerddapXtracto)
library(rerddap)
library(stars)
seadataset <- ed_search("sea ice concentration Northern", url = "https://polarwatch.noaa.gov/erddap/")
seadataset[1]
icedailyinfo <- info("nsidcG02202v4nh1day", url = "https://polarwatch.noaa.gov/erddap/")
icedailyinfo
parameter <- "cdr_seaice_conc"
## EPSG::3411
tpos <- c("2017-06-01")


AK <- c(-151.03, 70.35) # Alpine, Alaska
AK_st <- st_sfc(st_point(AK))
st_crs(AK_st) <- 4326
AK_polar <- st_transform(AK_st, st_crs("EPSG:3411"))
AK_buffer <- st_buffer(AK_polar, 
                       dist = 300000)
ggplot() + geom_sf(data=AK_buffer) + geom_sf(data = AK_polar)


seaicebuffer <- rxtractogon(icedailyinfo, parameter=parameter, 
                            xcoord = st_coordinates(AK_buffer)[,"X"],
                            ycoord = st_coordinates(AK_buffer)[,"Y"],
                            tcoord = tpos,
                            xName = "xgrid",
                            yName = "ygrid",
                            verbose = TRUE)
```

I get the following messages and error:

0s 0s* Hostname polarwatch.noaa.gov was found in DNS cache                                                  0s
*   Trying 161.55.160.18...
* TCP_NODELAY set
* Connected to polarwatch.noaa.gov (161.55.160.18) port 443 (#9)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=La Jolla; O=Southwest Fisheries Science Center; CN=polarwatch.noaa.gov
*  start date: Dec 13 00:00:00 2021 GMT
*  expire date: Jan 13 23:59:59 2023 GMT
*  subjectAltName: host "polarwatch.noaa.gov" matched cert's "polarwatch.noaa.gov"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
> GET /erddap/griddap/nsidcG02202v4nh1day.nc?cdr_seaice_conc[(2017-06-01T00:00:00Z):1:(2017-06-01T00:00:00Z)][(887500):1:(287500)][(-2362500):1:(-1762500)] HTTP/1.1
Host: polarwatch.noaa.gov
User-Agent: libcurl/7.64.1 r-curl/4.3.2 crul/1.2.0
Accept-Encoding: gzip, deflate
Accept: application/json, text/xml, application/xml, */*

< HTTP/1.1 200 
< Date: Sat, 15 Jan 2022 18:00:01 GMT
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< Last-Modified: Sat, 15 Jan 2022 18:00:01 GMT
< xdods-server: dods/3.7
< erddap-server: 2.14
< Content-Disposition: attachment;filename=nsidcG02202v4nh1day_ee20_8680_b49f.nc
< Content-Encoding: gzip
< Content-Type: application/x-netcdf
< Connection: close
< Transfer-Encoding: chunked
< 
* Closing connection 9
Error in matrix(rep(extract$longitude, length(extract$latitude)), ncol = length(extract$latitude)) : 
  'data' must be of a vector type, was 'NULL'

I have also tried without changing the `xName` and `yName` arguments, but then I get the error: "Requested coordinate names do no match dataset coordinate names"

I have followed the Ch8 tutorial here: https://coastwatch.pfeg.noaa.gov/projects/r/Projected.html and while I can get the array data, then I'm not sure how to manipulate it so as to extract the value in the buffer.

Any help would be really appreciated!!

Best,

Marie

**Comment by MarieAugerMethe** [comment]
A few pieces of additional info.

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)


rerddap v0.8.0
rerddapXtracto v1.1.2

**Comment by rmendels** [comment]
@MarieAugerMethe - Thanks.  So I can reproduce it,  there must be a missing 'library()' command because I get all the "st_" related commands as undefined. Once I can reproduce it,  I will check what is going on later today,  but if I had to make a quick guess it would be that rxtractogon() only works with lat-lon-time.  If so,  I need to put in a check and put out an error and stop the program.  If you want to do this yourself,  just use 'rerddap'  or download.file()  to get the URL https://polarwatch.noaa.gov//erddap/griddap/nsidcG02202v4nh1day.nc?cdr_seaice_conc[(2017-06-01T00:00:00Z):1:(2017-06-01T00:00:00Z)][(887500):1:(287500)][(-2362500):1:(-1762500)] 

and then find an R function that checks for presence in a polygon that isn't restricted to lat-lon.  I believe  (but will have to check) that the one I use is restricted to lat-lon.

**Comment by MarieAugerMethe** [comment]
Thanks and sorry!

library(sf)
library(ggplot2)
library(rerddapXtracto)
library(rerddap)
library(stars)


I will also update above

**Comment by MarieAugerMethe** [comment]
I may be making headways with using `rxtracto_3D` instead of `rxtractogon`, but not sure yet.

**Comment by rmendels** [comment]
@MarieAugerMethe Thanks.  I notice that in the manual page you cite they show how to pull down the lat-lon values for the grid  (they will not be an even grid).  I believe either 'st' or 'sf' have functions to check whether a point is inside or outside a polygon,  I just am not certain if they can handle an uneven grid.  But I believe they can handle projected data,  just try passing the them the data and the projection information.  Either way,  I need to add a check for this in my code.

**Comment by MarieAugerMethe** [comment]
Thanks @rmendels !! I think that if we are in the good projection (here EPSG::3411), it should be an even grid. Just not even in terms of Lat/Lon (I maybe confused though). Are you saying that your package only deals with lat/lon? I'm able to extract info with rxtracto_3D now, I'm just unsure if it's correct yet. I'll update once I managed to figure out if it's ok (or not).

**Comment by MarieAugerMethe** [comment]
Here is what I have with `rxtracto`

```
library(sf)
library(ggplot2)
library(rerddapXtracto)
library(rerddap)
library(stars)
seadataset <- ed_search("sea ice concentration Northern", url = "https://polarwatch.noaa.gov/erddap/")
seadataset[1]
icedailyinfo <- info("nsidcG02202v4nh1day", url = "https://polarwatch.noaa.gov/erddap/")
icedailyinfo
parameter <- "cdr_seaice_conc"
## EPSG::3411
tpos <- c("2017-04-01", "2017-04-03")


AK <- c(-151.03, 70.35) # Alpine, Alaska
AK_st <- st_sfc(st_point(AK))
st_crs(AK_st) <- 4326
AK_polar <- st_transform(AK_st, st_crs("EPSG:3411"))
AK_buffer <- st_buffer(AK_polar, 
                       dist = 300000)
ggplot() + geom_sf(data=AK_buffer) + geom_sf(data = AK_polar)

seaicebuffer <- rxtracto_3D(icedailyinfo, parameter=parameter, 
                            xcoord = st_coordinates(AK_buffer)[,"X"],
                            ycoord = st_coordinates(AK_buffer)[,"Y"],
                            tcoord = tpos,
                            xName = "xgrid",
                            yName = "ygrid",
                            verbose = TRUE)



class(seaicebuffer)
seaicebuffer
```


$cdr_seaice_conc
, , 1

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14] [,15]
[1,]    1    1    1    1    1    1    1    1    1     1     1     1     1     1     1
     [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
[1,]     1     1     1     1     1     1     1     1     1     1

, , 2

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14] [,15]
[1,]    1    1    1    1    1    1    1    1    1     1     1     1     1     1     1
     [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
[1,]     1     1     1     1     1     1     1     1     1     1

, , 3

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14] [,15]
[1,]    1    1    1    1    1    1    1    1    1     1     1     1     1     1     1
     [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25]
[1,]     1     1     1     1     1     1     1     1     1     1


$datasetname
[1] "nsidcG02202v4nh1day"

$xgrid
[1] -1762500

$ygrid
 [1] 887500 862500 837500 812500 787500 762500 737500 712500 687500 662500 637500 612500
[13] 587500 562500 537500 512500 487500 462500 437500 412500 387500 362500 337500 312500
[25] 287500

$altitude
[1] NA

$time
[1] "2017-04-01 GMT" "2017-04-02 GMT" "2017-04-03 GMT"

attr(,"class")
[1] "list"       "rxtracto3D"

I'm was pretty excited about it! But maybe it's a dead end again. The main thing that I can't wrap my head around is why there is only one xgrid value.

I'll try the download.file option. I do really like your package and was hoping that I could work this through it.

**Comment by MarieAugerMethe** [comment]
Hi again (and sorry!)

I digged a bit in the code of [rxtracto_3D.R](https://github.com/rmendels/rerddapXtracto/blob/a23d48eff05d948244610a3b8c14cc1a5f9877bd/R/rxtracto_3D.R). I was curious, why are the xcoordLim (Line 81) and ycoordLim (Line 87) are different? I think this is the reason why `findERDDAPcoord()` (Line 118) returns only one x coordinate value (repeated twice) in $erddapXcoord.

By changing line 81 to:
```
xcoordLim <- c(min(working_coords$xcoord1), max(working_coords$xcoord1)) 
```

give coordinates that works, I think. Not sure if making that change would affect other functions of your package.

But I’m have a hard time to convert the data to a usable object since meltnc is written in terms of lat and lon and I think also just having a hard time to make the extracted data into a raster or spatial grid.

Thanks for all the help!

**Comment by rmendels** [comment]
@MarieAugerMethe The reason the the two differ is that longitudes may get remapped,  so limit is calculated in that function, while latitudes are not.  But that is not your problem.  

```r
AK <- c(-151.03, 70.35) # Alpine, Alaska
> AK_st <- st_sfc(st_point(AK))
> st_crs(AK_st) <- 4326
> AK_polar <- st_transform(AK_st, st_crs("EPSG:3411"))
> AK_buffer <- st_buffer(AK_polar, 
+                        dist = 300000)
> ggplot() + geom_sf(data=AK_buffer) + geom_sf(data = AK_polar)
> 
> st_coordinates(AK_buffer)[,"X"]
  [1] -1765346 -1765757 -1766989 -1769039 -1771902 -1775568
  [7] -1780029 -1785272 -1791282 -1798044 -1805538 -1813745
 [13] -1822641 -1832202 -1842402 -1853214 -1864607 -1876550
 [19] -1889010 -1901954 -1915346 -1929149 -1943325 -1957835
 [25] -1972641 -1987700 -2002972 -2018416 -2033987 -2049645
 [31] -2065346 -2081047 -2096704 -2112276 -2127719 -2142992
 [37] -2158051 -2172856 -2187367 -2201543 -2215346 -2228738
 [43] -2241681 -2254142 -2266085 -2277478 -2288289 -2298490
 [49] -2308051 -2316947 -2325153 -2332648 -2339409 -2345420
 [55] -2350663 -2355124 -2358790 -2361652 -2363702 -2364935
 [61] -2365346 -2364935 -2363702 -2361652 -2358790 -2355124
 [67] -2350663 -2345420 -2339409 -2332648 -2325153 -2316947
 [73] -2308051 -2298490 -2288289 -2277478 -2266085 -2254142
 [79] -2241681 -2228738 -2215346 -2201543 -2187367 -2172856
 [85] -2158051 -2142992 -2127719 -2112276 -2096704 -2081047
 [91] -2065346 -2049645 -2033987 -2018416 -2002972 -1987700
 [97] -1972641 -1957835 -1943325 -1929149 -1915346 -1901954
[103] -1889010 -1876550 -1864607 -1853214 -1842402 -1832202
[109] -1822641 -1813745 -1805538 -1798044 -1791282 -1785272
[115] -1780029 -1775568 -1771902 -1769039 -1766989 -1765757
[121] -1765346
```

rxtracto_3D wants a bounding box.    If instead do:

```r
xcoord <- c(min(st_coordinates(AK_buffer)[,"X"]), max(st_coordinates(AK_buffer)[,"X"]))
ycoord <- c(min(st_coordinates(AK_buffer)[,"Y"]), max(st_coordinates(AK_buffer)[,"Y"]))
seaicebuffer <- rxtracto_3D(icedailyinfo, parameter=parameter, 
                          xcoord = xcoord, 
                          ycoord = ycoord,
                           tcoord = tpos,
                           xName = "xgrid",
                           yName = "ygrid")
str(seaicebuffer)
List of 6
 $ cdr_seaice_conc: num [1:25, 1:25, 1:3] NA NA NA NA NA NA NA NA NA NA ...
 $ datasetname    : chr "nsidcG02202v4nh1day"
 $ xgrid          : num [1:25(1d)] -2362500 -2337500 -2312500 -2287500 -2262500 ...
 $ ygrid          : num [1:25(1d)] 887500 862500 837500 812500 787500 ...
 $ altitude       : logi NA
 $ time           : POSIXlt[1:3], format: "2017-04-01" ...
 - attr(*, "class")= chr [1:2] "list" "rxtracto3D"
>
```

Hope this helps.

**Comment by rmendels** [comment]
@MarieAugerMethe - I should add that I believe,  as shown above,  that only rxtractogon is limited to lat-lon-time - it actual does the initial extract fine,  it fails in the call to see which points lie in the polygon.

HTH.

**Comment by MarieAugerMethe** [comment]
Thanks @rmendels !! Yes, I figured that rxtracto_3D was a bounding box (after writting). Great to know re rxtractogon, I will dig a bit more. Many many many thanks!

**Comment by rmendels** [comment]
@MarieAugerMethe  Great.  As I said,  all you need to do now is pass the array to something that can determine if points are within a polygon,  and mark the points outside with NA or something similar..  I haven't had a chance to see exactly what is limiting in what I use in rxtractogon (I do know the data get downloaded - that step worked) ,  and if there are better functions to use now,  but today is a Federal holiday so I may not get to it.  I am going to mark this as closed.  Good luck on your research.

**Comment by rmendels** [comment]
@MarieAugerMethe - I reopened this because I just took a quick look at the code,  I limit it to lat-lon,  not the function I use.  Something I can probably fix down the line, or at least add check.  I pass the data array to sp::point.in.polygon(), but these days with all the new spatial packages there likely one that may be faster.

**Comment by MarieAugerMethe** [comment]
Ok, thanks! I just forked your repo, and was checking if I could modified some functions to make them more general (I think a few use $latitude $longitude and changing that to something more general would open up to more datasets (but this is quite outside my expertise ;) ).

**Comment by rmendels** [comment]
@MarieAugerMethe - where it gets tricky, and I was probably being lazy,  is obtaining and using the names of the xcoord and ycoord. Right now,  it would probably be a lot faster for you to just write a short script to use rxtracto_3D() to get the data and then pass it yourself to sp::point.in.polygon() or some such.  After all,  that is all my code does,  the difference being that for CRAN I have to put in all sorts of checks that the user hasn't passed nonsense and that the intermediate steps worked.

**Comment by MarieAugerMethe** [comment]
Yes, I think that's what I'm doing. Unless I'm missing something. To be able to create a spatial object I have to pass it through something like meltnc(), no?
That's what I playing around now.

**Comment by rmendels** [comment]
@MarieAugerMethe - I don't think you need that extra step, depending on which function you use.  Take a look at the code in rxtractogon() starting at line 123. Or,  if you need the data "melted" for the function you want to use,  use rerddap::griddap() to get the data,  that function "melts" the data by default.

**Comment by MarieAugerMethe** [comment]
Just FYI, I think this makes `meltnc` general

```
meltnc <- function(resp, xName = 'longitude', yName = 'latitude', tName = 'time'){
  ##  modified from rerddap::ncdf4_get
  rows <- length(resp[[1]])
  # if no time coordinate, use expand.grid to expand ut lat-lon grid
  if (is.null(resp$time)) {
    exout <- do.call("expand.grid", list(x = resp[[xName]],
                                         y = resp[[yName]]))
    names(exout) <- c(xName, yName)
     # meta <- dplyr::arrange_(exout, names(exout)[1])
    meta <- dplyr::arrange(exout, names(exout)[1])
  } else {
    # need to expand grid along all three dimensions to melt to data frame
    time <- as.character(resp[[tName]])
    time <- suppressWarnings(rep(time, each = rows/length(resp[[tName]])))
    y <- rep(rep(resp[[yName]], each = length(resp[[xName]])),
               length(resp[[tName]]))
    x <- rep(rep(resp[[xName]], times = length(resp[[yName]])),
               times = length(resp[[tName]]))
    meta <- data.frame(time, x, y, stringsAsFactors = FALSE)
    names(meta) <- c(tName, xName, yName)
  }

  # make data.frame
  df <- as.vector(resp[[1]])
  df <- data.frame(df)
  names(df) <- names(resp)[1]
  alldf <- if (NROW(meta) > 0) cbind(meta, df) else df

  #  Fool plotdap that there is a summary
  summary_time <- list(vals = as.numeric(resp[[tName]]))
  summary_x <- list(vals = resp[[xName]])
  summary_y <- list(vals = resp[[yName]])
  dims <- list(time = summary_time, x = summary_x,
               y = summary_y)
  names(dims) <- c(tName, xName, yName)
  summary <- list(dims)
  names(summary) <- 'dim'
  # output a list that looks like an rerddap list
  list(summary = summary, data = alldf)
}
```

I can push it if you'd like.

**Comment by MarieAugerMethe** [comment]
Oops, we wrote at the same time.

**Comment by rmendels** [comment]
@MarieAugerMethe -Thanks for the code.  I may use that,  if i do will put you down as a contributor, so you don't need to push it.  But "meltnc()" isn't where the code fails,  it fails because of the lines:

```r
x.vals <- matrix(rep(extract$longitude, length(extract$latitude)),
                 ncol = length(extract$latitude))
y.vals <- sort(rep(extract$latitude, length(extract$longitude)))
y.vals <- matrix(y.vals, nrow = length(extract$latitude),
                 ncol = length(extract$longitude))
```

**Comment by MarieAugerMethe** [comment]
Yes, I was sticking with the bounding box for now and trying to create a raster (so going from 

```
xcoord <- c(min(st_coordinates(AK_buffer)[,"X"]), max(st_coordinates(AK_buffer)[,"X"]))
ycoord <- c(min(st_coordinates(AK_buffer)[,"Y"]), max(st_coordinates(AK_buffer)[,"Y"]))
seaicebuffer <- rxtracto_3D(icedailyinfo, parameter=parameter, 
                            xcoord = xcoord, 
                            ycoord = ycoord,
                            tcoord = tpos,
                            xName = "xgrid",
                            yName = "ygrid")

sea.ice.grid <- meltnc(seaicebuffer, xName = 'xgrid', yName = 'ygrid', tName = 'time')
```

For the code above, we could use some of the same tricks (let me check). 

It would be amazing if you could include some of the changes (as long as you check it - again it's not my expertise). I think many researchers (at least all of my students/postdocs and many of my collabs) will be excited to see your package work with sea ice data ;) We love your package and work with sea ice all the time ;)

**Comment by MarieAugerMethe** [comment]
The above lines can be changed to

```
x.vals <- matrix(rep(extract[[xName]], length(extract[[yName]])),
                 ncol = length(extract[[yName]]))
y.vals <- sort(rep(extract[[yName]], length(extract[[xName]])))
y.vals <- matrix(y.vals, nrow = length(extract[[yName]]),
                 ncol = length(extract[[xName]]))
```

But then I get an error at line 138

Error in matrix(sp::point.in.polygon(x.vals, y.vals, mypoly$x, mypoly$y),  : 
  data is too long

**Comment by rmendels** [comment]
Planning on looking at what you have sent.  The problem is, as you will,  that if i am posting things in a package I have to do a lot of testing to make certain that the code works in all situations  (which clearly I have missed at some points), and ERDDAP handles all sorts of data,  with lots of crazy grids,  and where the coordinate value may be increasing or decreasing.  I am old and lazy and that sort of stuff is tedious.  The class tutorials will show how you can use what works now,  using plotting functions from the package 'oce'  (or in fact ggplot2 can now handle some projections) with sea ice data.

I am pleased you and your students like the package and find it of use. Our whole premise is that data should be readily accessible and easy to use,  and people should not need secret handshakes to get the data, nor have to pay for it, and can work in their applications of choice.

**Comment by MarieAugerMethe** [comment]
Yes, I understand re testing things!!! That's my hesitation to push things. But if you find the energy, we will be excited ;) Extracting environmental data can be so tedious at time (I'm just now trying to reply to a "simple request from a reviewer" ;))

For Line 138-139, I fixed it to 

```
in.poly <- matrix(sp::point.in.polygon(x.vals, y.vals, mypoly$x, mypoly$y),
                  ncol = length(extract[[xName]]))
```

Let me know if you want me to push (and I completely understand if you feel it's too much to check).

Many many thanks!!

**Comment by rmendels** [comment]
@MarieAugerMethe - Thanks again for the code.  I am not great with Git,  which is why sometimes I don't like pull requests because I mess things up.  But if you can, can you make a pull request to the "development' branch,  not the main branch.  I try to keep the main branch for things I know what I have tested and where things might be wrong.

**Comment by MarieAugerMethe** [comment]
I tried but for some reason it's not working. Looks like it's a permission issue (I'm also not great with Github). Here are the files I changed.
[ForRoy.zip](https://github.com/rmendels/rerddapXtracto/files/7883880/ForRoy.zip)

**Comment by rmendels** [comment]
@MarieAugerMethe Thanks!  I will probably add those to the development branch some time today,  and push them to Github.  Right now,  the Development branch and main branch should be the same,  though as I said I know just enough about Git and Github to be dangerous.  Worse,  if it all works,  I will have to go CRAN again,  which while I appreciate everything CRAN is trying to do,  I try to avoid.  One of my few claims to fame is that I have been "Ripleyed" 4-5 times.

**Comment by MarieAugerMethe** [comment]
Thanks!!
Just to make sure you don't get Ripleyed again (so funny), note that I have not changed any of the headers and things describing the arguments. I've really just changed the functions. Thanks!!

**Comment by rmendels** [comment]
@MarieAugerMethe - I just did a quick test and your patches appear to make rxtractogon() work with your example.  However,  plotBBox() will not work because at the moment it is restricted to lat-lon.  However  (and maybe I am jumping the gun on the course), see https://github.com/CoastWatch-WestCoast/r_code/blob/master/mapping_projected_datasets.md.

I just pushed your patches to the development branches,  but caveat emptor,  since it it has only been tested on one case.  The vignette appears to work fine.

**Comment by MarieAugerMethe** [comment]
Great, thanks. No problem re plotBBox. I figured out how to plot it and I'm all set now. Thanks so much! I shared with my students that they may be able to use your package to extract sea ice data and they were happy ;)

If I get time, I can try to generalize your other functions... but for now I'm all good.
