### ISSUE TITLE
note about caching change in rerddap

### ISSUE THREAD

**Issue by sckott** [rmendels/rerddapXtracto#4]
note https://github.com/ropensci/rerddap/issues/43 

going to change caching mechanism, in which case we'll remove ability to set cache path, and instead `rappdirs` will do that, so may need to change your code a bit

**Comment by rmendels** [comment]
I use the information in the return from the function (griddap, tabledap) to know where the file is stored.  If that doesn't change, then I am still good.   So I don't assume anything about the path to the cache.

-Roy

**Comment by sckott** [comment]
but e.g, https://github.com/rmendels/rerddapXtracto/blob/master/R/rxtracto.R#L316 would need to change

**Comment by rmendels** [comment]
Thank you.  I will check the others to see if I am deleting knowing the cache or reading from the return information.  And thanks for the time at looking at these.  It is big help.  It is always good to have other sets of eyes look at things.

-Roy

> On Jan 4, 2017, at 10:11 AM, Scott Chamberlain <notifications@github.com> wrote:
> 
> but e.g, https://github.com/rmendels/rerddapXtracto/blob/master/R/rxtracto.R#L316 would need to change
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by sckott** [comment]
np!
