### ISSUE TITLE
Simplify code if possible?

### ISSUE THREAD

**Issue by sckott** [rmendels/rerddapXtracto#5]
The 3 main functions are all quite large - looking at them I get a bit lost, and if I wanted to contribute something (hypothetically) it's a little hard to understand. 

Could you break apart the functions into smaller bits that make sense?  e.g., in https://github.com/ropensci/rerddap/blob/master/R/grid.R the main function `griddap()`  could be a lot larger if we put all those other helper functions within `griddap` itself, but instead we broke apart all the logic into many functions that by themselves are hopefully easier to understand

if too much work, no worries

**Comment by rmendels** [comment]
Good suggestion,  have thought of that,  a lot depends on laziness (a very strong trait) and time versus wanting to get it out.

-Roy

> On Jan 4, 2017, at 10:07 AM, Scott Chamberlain <notifications@github.com> wrote:
> 
> The 3 main functions are all quite large - looking at them I get a bit lost, and if I wanted to contribute something (hypothetically) it's a little hard to understand.
> 
> Could you break apart the functions into smaller bits that make sense? e.g., in https://github.com/ropensci/rerddap/blob/master/R/grid.R the main function griddap() could be a lot larger if we put all those other helper functions within griddap itself, but instead we broke apart all the logic into many functions that by themselves are hopefully easier to understand
> 
> if too much work, no worries
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.
